name: Deploy Frontend to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hotel-inventory-frontend:latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Configure GKE credentials
        run: |
          gcloud config set project ${{ secrets.GKE_PROJECT }}
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f https://raw.githubusercontent.com/sar-avana/hotel-inventory-infra/main/k8s/frontend-deployment.yaml
          kubectl apply -f https://raw.githubusercontent.com/sar-avana/hotel-inventory-infra/main/k8s/frontend-service.yaml
