name: Frontend CI/CD Pipeline - Prod

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hotel-inventory-frontend:${{ github.sha }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: prod-cluster
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Replace version tag in deployment manifest
        run: |
          sed -i "s|<VERSION_TAG>|${{ github.sha }}|g" k8s/prod/frontend-deployment.yml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/prod/frontend-service.yml --validate=false
          kubectl apply -f k8s/prod/frontend-deployment.yml --validate=false

      - name: Rollout restart frontend deployment
        run: kubectl rollout restart deployment frontend --namespace=default
